services:
  catego-redis:
    container_name: catego-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: bzzni/catego-redis
    ports:
      - "6379:6379"
  catego-app:
    container_name: catego-app
    build: .
    depends_on:
      - catego-redis
    image: bzzni/catego-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./logs:/catego/logs
    ports:
      - "80:8080"
    restart: on-failure
