name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hyebeen/catego
          stage: main
          yaml: >
            name: catego

            app: java@17

            options:
              ports: 8080
              env:
                DB_IP: ${{ secrets.DB_IP }}
                DB_PORT: ${{ secrets.DB_PORT }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
